### PR TITLE
fix(arrayvalidator): fixed runaway type instantiation with TypeScript >=5.1

### PR DESCRIPTION
**Pull request by favna**
Related: https://github.com/microsoft/TypeScript/issues/54491

### CODE REVIEW

**Comment by favna** [comment]
@sapphiredev pack

**Review by vladfrangu — APPROVED** [review]
If it works, merge it

**Review by vladfrangu — APPROVED** [review]

**Comment by SuperchupuDev** [comment]
this fix can probably be reverted now that typescript 5.1.5 was released
- https://github.com/microsoft/TypeScript/issues/54491

**Comment by favna** [comment]
> this fix can probably be reverted now that typescript 5.1.5 was released

Fair point but because it's still an issue in older versions of TypeScript and we cannot be guaranteed that everyone uses caret versioning, or that their transitive dependencies are properly updated, we will keep the fix for now.

**Comment by SuperchupuDev** [comment]
alright but 5.1.3 is the only stable typescript version that had the problem, there are no other versions with the issue, updating to a new patch release shouldn't be that much of an problem? specially to fix a regression

**Comment by imranbarbhuiya** [comment]
Why does this pr need to revert tho? are there any issues with the current approach?

**Comment by vladfrangu** [comment]
Unless there are any glaring issues caused by this PR, we won't be reverting it any time soon, as (as far as we know) there are no issues with keeping it. Should that change, you're free to open an issue / revert

**Pull request merged**
